/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedCustomerRouteImport } from './routes/_authed.customer'
import { Route as AuthedContractorRouteImport } from './routes/_authed.contractor'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedCustomerIndexRouteImport } from './routes/_authed.customer.index'
import { Route as AuthedContractorIndexRouteImport } from './routes/_authed.contractor.index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed.admin.index'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed.admin.users.index'
import { Route as AuthedAdminTemplatesIndexRouteImport } from './routes/_authed.admin.templates.index'
import { Route as AuthedAdminOrganizationsIndexRouteImport } from './routes/_authed.admin.organizations.index'
import { Route as AuthedAdminOrdersIndexRouteImport } from './routes/_authed.admin.orders.index'
import { Route as AuthedCustomerOrdersNewRouteImport } from './routes/_authed.customer.orders.new'
import { Route as AuthedCustomerOrdersOrderIdRouteImport } from './routes/_authed.customer.orders.$orderId'
import { Route as AuthedContractorJobsOrderIdRouteImport } from './routes/_authed.contractor.jobs.$orderId'
import { Route as AuthedAdminTemplatesTemplateIdRouteImport } from './routes/_authed.admin.templates.$templateId'
import { Route as AuthedAdminOrdersOrderIdRouteImport } from './routes/_authed.admin.orders.$orderId'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomerRoute = AuthedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContractorRoute = AuthedContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomerIndexRoute = AuthedCustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCustomerRoute,
} as any)
const AuthedContractorIndexRoute = AuthedContractorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedContractorRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminTemplatesIndexRoute =
  AuthedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminOrganizationsIndexRoute =
  AuthedAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminOrdersIndexRoute = AuthedAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedCustomerOrdersNewRoute = AuthedCustomerOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthedCustomerRoute,
} as any)
const AuthedCustomerOrdersOrderIdRoute =
  AuthedCustomerOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthedCustomerRoute,
  } as any)
const AuthedContractorJobsOrderIdRoute =
  AuthedContractorJobsOrderIdRouteImport.update({
    id: '/jobs/$orderId',
    path: '/jobs/$orderId',
    getParentRoute: () => AuthedContractorRoute,
  } as any)
const AuthedAdminTemplatesTemplateIdRoute =
  AuthedAdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminOrdersOrderIdRoute =
  AuthedAdminOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/contractor': typeof AuthedContractorRouteWithChildren
  '/customer': typeof AuthedCustomerRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/contractor/': typeof AuthedContractorIndexRoute
  '/customer/': typeof AuthedCustomerIndexRoute
  '/admin/orders/$orderId': typeof AuthedAdminOrdersOrderIdRoute
  '/admin/templates/$templateId': typeof AuthedAdminTemplatesTemplateIdRoute
  '/contractor/jobs/$orderId': typeof AuthedContractorJobsOrderIdRoute
  '/customer/orders/$orderId': typeof AuthedCustomerOrdersOrderIdRoute
  '/customer/orders/new': typeof AuthedCustomerOrdersNewRoute
  '/admin/orders/': typeof AuthedAdminOrdersIndexRoute
  '/admin/organizations/': typeof AuthedAdminOrganizationsIndexRoute
  '/admin/templates/': typeof AuthedAdminTemplatesIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/no-access': typeof NoAccessRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/contractor': typeof AuthedContractorIndexRoute
  '/customer': typeof AuthedCustomerIndexRoute
  '/admin/orders/$orderId': typeof AuthedAdminOrdersOrderIdRoute
  '/admin/templates/$templateId': typeof AuthedAdminTemplatesTemplateIdRoute
  '/contractor/jobs/$orderId': typeof AuthedContractorJobsOrderIdRoute
  '/customer/orders/$orderId': typeof AuthedCustomerOrdersOrderIdRoute
  '/customer/orders/new': typeof AuthedCustomerOrdersNewRoute
  '/admin/orders': typeof AuthedAdminOrdersIndexRoute
  '/admin/organizations': typeof AuthedAdminOrganizationsIndexRoute
  '/admin/templates': typeof AuthedAdminTemplatesIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/contractor': typeof AuthedContractorRouteWithChildren
  '/_authed/customer': typeof AuthedCustomerRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/contractor/': typeof AuthedContractorIndexRoute
  '/_authed/customer/': typeof AuthedCustomerIndexRoute
  '/_authed/admin/orders/$orderId': typeof AuthedAdminOrdersOrderIdRoute
  '/_authed/admin/templates/$templateId': typeof AuthedAdminTemplatesTemplateIdRoute
  '/_authed/contractor/jobs/$orderId': typeof AuthedContractorJobsOrderIdRoute
  '/_authed/customer/orders/$orderId': typeof AuthedCustomerOrdersOrderIdRoute
  '/_authed/customer/orders/new': typeof AuthedCustomerOrdersNewRoute
  '/_authed/admin/orders/': typeof AuthedAdminOrdersIndexRoute
  '/_authed/admin/organizations/': typeof AuthedAdminOrganizationsIndexRoute
  '/_authed/admin/templates/': typeof AuthedAdminTemplatesIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/no-access'
    | '/admin'
    | '/contractor'
    | '/customer'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/contractor/'
    | '/customer/'
    | '/admin/orders/$orderId'
    | '/admin/templates/$templateId'
    | '/contractor/jobs/$orderId'
    | '/customer/orders/$orderId'
    | '/customer/orders/new'
    | '/admin/orders/'
    | '/admin/organizations/'
    | '/admin/templates/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/no-access'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/contractor'
    | '/customer'
    | '/admin/orders/$orderId'
    | '/admin/templates/$templateId'
    | '/contractor/jobs/$orderId'
    | '/customer/orders/$orderId'
    | '/customer/orders/new'
    | '/admin/orders'
    | '/admin/organizations'
    | '/admin/templates'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/no-access'
    | '/_authed/admin'
    | '/_authed/contractor'
    | '/_authed/customer'
    | '/_authed/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/admin/'
    | '/_authed/contractor/'
    | '/_authed/customer/'
    | '/_authed/admin/orders/$orderId'
    | '/_authed/admin/templates/$templateId'
    | '/_authed/contractor/jobs/$orderId'
    | '/_authed/customer/orders/$orderId'
    | '/_authed/customer/orders/new'
    | '/_authed/admin/orders/'
    | '/_authed/admin/organizations/'
    | '/_authed/admin/templates/'
    | '/_authed/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  NoAccessRoute: typeof NoAccessRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customer': {
      id: '/_authed/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthedCustomerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contractor': {
      id: '/_authed/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof AuthedContractorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customer/': {
      id: '/_authed/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof AuthedCustomerIndexRouteImport
      parentRoute: typeof AuthedCustomerRoute
    }
    '/_authed/contractor/': {
      id: '/_authed/contractor/'
      path: '/'
      fullPath: '/contractor/'
      preLoaderRoute: typeof AuthedContractorIndexRouteImport
      parentRoute: typeof AuthedContractorRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/templates/': {
      id: '/_authed/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/organizations/': {
      id: '/_authed/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthedAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/orders/': {
      id: '/_authed/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/customer/orders/new': {
      id: '/_authed/customer/orders/new'
      path: '/orders/new'
      fullPath: '/customer/orders/new'
      preLoaderRoute: typeof AuthedCustomerOrdersNewRouteImport
      parentRoute: typeof AuthedCustomerRoute
    }
    '/_authed/customer/orders/$orderId': {
      id: '/_authed/customer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/customer/orders/$orderId'
      preLoaderRoute: typeof AuthedCustomerOrdersOrderIdRouteImport
      parentRoute: typeof AuthedCustomerRoute
    }
    '/_authed/contractor/jobs/$orderId': {
      id: '/_authed/contractor/jobs/$orderId'
      path: '/jobs/$orderId'
      fullPath: '/contractor/jobs/$orderId'
      preLoaderRoute: typeof AuthedContractorJobsOrderIdRouteImport
      parentRoute: typeof AuthedContractorRoute
    }
    '/_authed/admin/templates/$templateId': {
      id: '/_authed/admin/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AuthedAdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/orders/$orderId': {
      id: '/_authed/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminOrdersOrderIdRoute: typeof AuthedAdminOrdersOrderIdRoute
  AuthedAdminTemplatesTemplateIdRoute: typeof AuthedAdminTemplatesTemplateIdRoute
  AuthedAdminOrdersIndexRoute: typeof AuthedAdminOrdersIndexRoute
  AuthedAdminOrganizationsIndexRoute: typeof AuthedAdminOrganizationsIndexRoute
  AuthedAdminTemplatesIndexRoute: typeof AuthedAdminTemplatesIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminOrdersOrderIdRoute: AuthedAdminOrdersOrderIdRoute,
  AuthedAdminTemplatesTemplateIdRoute: AuthedAdminTemplatesTemplateIdRoute,
  AuthedAdminOrdersIndexRoute: AuthedAdminOrdersIndexRoute,
  AuthedAdminOrganizationsIndexRoute: AuthedAdminOrganizationsIndexRoute,
  AuthedAdminTemplatesIndexRoute: AuthedAdminTemplatesIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedContractorRouteChildren {
  AuthedContractorIndexRoute: typeof AuthedContractorIndexRoute
  AuthedContractorJobsOrderIdRoute: typeof AuthedContractorJobsOrderIdRoute
}

const AuthedContractorRouteChildren: AuthedContractorRouteChildren = {
  AuthedContractorIndexRoute: AuthedContractorIndexRoute,
  AuthedContractorJobsOrderIdRoute: AuthedContractorJobsOrderIdRoute,
}

const AuthedContractorRouteWithChildren =
  AuthedContractorRoute._addFileChildren(AuthedContractorRouteChildren)

interface AuthedCustomerRouteChildren {
  AuthedCustomerIndexRoute: typeof AuthedCustomerIndexRoute
  AuthedCustomerOrdersOrderIdRoute: typeof AuthedCustomerOrdersOrderIdRoute
  AuthedCustomerOrdersNewRoute: typeof AuthedCustomerOrdersNewRoute
}

const AuthedCustomerRouteChildren: AuthedCustomerRouteChildren = {
  AuthedCustomerIndexRoute: AuthedCustomerIndexRoute,
  AuthedCustomerOrdersOrderIdRoute: AuthedCustomerOrdersOrderIdRoute,
  AuthedCustomerOrdersNewRoute: AuthedCustomerOrdersNewRoute,
}

const AuthedCustomerRouteWithChildren = AuthedCustomerRoute._addFileChildren(
  AuthedCustomerRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedContractorRoute: typeof AuthedContractorRouteWithChildren
  AuthedCustomerRoute: typeof AuthedCustomerRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedContractorRoute: AuthedContractorRouteWithChildren,
  AuthedCustomerRoute: AuthedCustomerRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  NoAccessRoute: NoAccessRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
